name: CI Pipeline

on: [ push, pull_request ]

jobs:


  install_dev:
    name: Install Dev Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Install Dependencies
        run: make dev -B

  # ------------------------------------------------------------------------------------------------------------------------

  syntax_checks:
    name: Syntax Checks
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: PHP Syntax Checks
        run: find . -name '*.php' -not -path "./src/vendor/*" -not -path "./tests/*" | xargs -n 1 -P4 php -l

  unit_tests:
    name: Unit Tests
    needs: install_dev
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Run PHPUnit
        run: make phpunit -B

  # ------------------------------------------------------------------------------------------------------------------------

  phpstan:
    name: PHPStan Analyzer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Run PHPStan
        run: make stan -B

  phpcsfixer:
    name: PHP CS Fixer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Run PHP CS Fixer
        run: make csfix -B


  build:
    name: Build Binaries
    needs: [ syntax_checks, unit_tests, phpstan, phpcsfixer ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Install Dependencies
        run: make build -B


  test_bin:
    name: E2E Tests | bin/svrunit
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Start Tests
        run: |
          cd tests/e2e && make bin -B


  test_phar:
    name: E2E Tests | svrunit.phar
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Start Tests
        run: |
          cd tests/e2e && make phar -B
