name: Release Pipeline

on: [ workflow_dispatch ]


jobs:

  syntax_checks:
    name: Syntax Checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: PHP Syntax Checks
        run: find . -name '*.php' -not -path "./src/vendor/*" -not -path "./tests/*" | xargs -n 1 -P4 php -l

  # ------------------------------------------------------------------------------------------------------------------------

  unit_tests:
    name: Unit Tests
    needs: syntax_checks
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: make dev -B

      - name: Run PHPUnit
        run: make test -B

  # ------------------------------------------------------------------------------------------------------------------------

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:

      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          ini-values: phar.readonly=OFF

      - name: Install Dependencies
        run: make build -B

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r svrunit.zip ./build/svrunit.phar

      - name: Prepare Files
        run: |
          rm -rf ./build/svrunit.phar
          mv svrunit.zip ./build/svrunit.zip

      - name: Deployment to Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.SSH_PROD_HOST }}
          port: ${{ secrets.SSH_PROD_PORT }}
          username: ${{ secrets.SSH_PROD_USER }}
          password: ${{ secrets.SSH_PROD_PWD }}
          local_dir: ./build/
          remote_dir: ${{ secrets.PROD_DOWNLOAD_DIR }}
          dry-run: false