name: Release Pipeline

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:


  install_dev:
    name: Install Dev Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Install Dependencies
        run: make dev -B

  # ------------------------------------------------------------------------------------------------------------------------

  syntax_checks:
    name: Syntax Checks
    needs: install_dev
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: PHP Syntax Checks
        run: find . -name '*.php' -not -path "./src/vendor/*" -not -path "./tests/*" | xargs -n 1 -P4 php -l

  unit_tests:
    name: Unit Tests
    needs: install_dev
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Run PHPUnit
        run: make phpunit -B

  # ------------------------------------------------------------------------------------------------------------------------

  phpstan:
    name: PHPStan Analyzer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Run PHPStan
        run: make stan -B

  phpcsfixer:
    name: PHP CS Fixer
    needs: install_dev
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Run PHP CS Fixer
        run: make csfix -B

  # ------------------------------------------------------------------------------------------------------------------------

  install_prod:
    name: Install Prod Dependencies
    needs: [ syntax_checks, unit_tests, phpstan, phpcsfixer ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Install Dependencies
        run: make install -B

  # ------------------------------------------------------------------------------------------------------------------------

  test_bin:
    name: E2E Tests | bin/svrunit
    runs-on: ubuntu-latest
    needs: [ install_prod ]
    steps:

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          ini-values: phar.readonly=OFF

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Start Tests
        run: |
          cd tests/e2e && make bin -B

  test_phar:
    name: E2E Tests | svrunit.phar
    runs-on: ubuntu-latest
    needs: [ install_prod ]
    steps:

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          ini-values: phar.readonly=OFF

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Build SVRUnit
        run: make build -B

      - name: Start Tests
        run: |
          cd tests/e2e && make phar -B

  # ------------------------------------------------------------------------------------------------------------------------

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [ test_bin, test_phar ]
    steps:

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          ini-values: phar.readonly=OFF

      - name: Mount Cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor

      - name: Build SVRUnit
        run: make build -B

      - name: Build Release ZIP file
        run: make release -B

      - name: Show Files
        run: |
          pwd
          ls -la ./build

      - name: Deployment to Server
        uses: bayssmekanique/action-simple-file-upload@v1
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          user: ${{ secrets.SSH_PROD_USER }}
          password: ${{ secrets.SSH_PROD_PWD }}
          src: ./build/svrunit.zip
          dest: ${{ secrets.PROD_DOWNLOAD_DIR }}/svrunit.zip

  packagist:
    name: Update Packagist
    runs-on: ubuntu-latest
    needs: [ deploy ]
    steps:

      - uses: actions/checkout@v3

      - name: Invoke Packagist Webhook
        run: |
          curl -XPOST -H'content-type:application/json' 'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USER }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}' -d'{"repository":{"url":"https://packagist.org/packages/svrunit/svrunit"}}'
